"""Add repos to SessionType enum

Revision ID: 01dc768cd4c2
Revises: 38f96ad2f27b
Create Date: 2025-06-25 15:05:05.595299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01dc768cd4c2'
down_revision: Union[str, None] = '38f96ad2f27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE sessiontype ADD VALUE 'repos'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### NOTE: Downgrading this migration is not straightforward
    # ### as it involves removing a value from an ENUM type, which can fail
    # ### if the value is in use. A manual data migration would be needed.
    pass
    # ### end Alembic commands ###
