"""add_strava_activities

Revision ID: ab94af18d6c0
Revises: d4f9b5bd7d80
Create Date: 2025-06-25 13:53:41.746345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab94af18d6c0'
down_revision: Union[str, None] = 'd4f9b5bd7d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strava_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strava_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('moving_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strava_activities_id'), 'strava_activities', ['id'], unique=False)
    op.create_index(op.f('ix_strava_activities_strava_id'), 'strava_activities', ['strava_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strava_activities_strava_id'), table_name='strava_activities')
    op.drop_index(op.f('ix_strava_activities_id'), table_name='strava_activities')
    op.drop_table('strava_activities')
    # ### end Alembic commands ###
